services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: events
    volumes:
      - postgres_data:/var/lib/postgresql/data # Перзистирање на податоци

volumes:
  postgres_data:
